packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  electron: true
  esbuild: true
  node-pty: true
  protobufjs: true
  sharp: true

onlyBuiltDependencies:
  - electron
  - esbuild
  - node-pty
  - sharp
